'use client'
import { ThemeProvider, createGlobalStyle } from 'styled-components';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const GlobalStyle = createGlobalStyle`
  body {
    background: ${({theme}) => theme.colors.dark};
  }
`;

const theme = {
  colors: {
    light: '#FFFFFF',
    dark: '#1B1C1E',
    grey: '#D1D2D2',
    yellow: '#E59500',
    lowYellow: 'rgba(229,149,0,0.20)',
    background: 'linear-gradient(180deg, #FAF5EC 5.60%, #FCD58D 81.63%)'
  }
}


export default function RootLayout({ children }) {
  return (
    <ThemeProvider theme={theme}>
      <GlobalStyle />
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ThemeProvider>
  )
}
